services:
  backend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - EMBEDDER_LOCAL_FILES_ONLY=false
    volumes:
      - .:/app
      - model_cache:/tmp/vector
    networks:
      - app-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - DOCKER_ENV=true
    volumes:
      - ./front:/front
      - /front/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  model_cache: