analysis_queries:
  fundamental:  # 10-K documents
    all_sections:
      queries:
        - "risk factors regulatory competitive operational threats challenges"
        - "business operations revenue model competitive advantages market position"
        - "financial statements revenue income balance sheet cash flow debt"
        - "management discussion analysis outlook guidance strategy MD&A"
      prompt_name: "fundamental_analysis"
  
  momentum:  # 10-Q documents
    all_sections:
      queries:
        - "business operations developments products services expansion quarterly updates"
        - "financial performance revenue margins liquidity costs quarterly results"
        - "risk factors emerging threats regulatory competitive short term challenges"
      prompt_name: "momentum_analysis"
  
  sentiment:  # News
    market_news:
      query: "{ticker} earnings revenue stock price announcement news"
      prompt_name: "sentiment_analysis"